set_property SRC_FILE_INFO {cfile:C:/Users/iqbal.ha/project_1/project_1.srcs/constrs_1/new/BingBong.xdc rfile:../../../project_1.srcs/constrs_1/new/BingBong.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets AES_PowerMon_i/Power_Monitor_0/inst/RO[0]/nolabel_line64/nolabel_line77/out]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets AES_PowerMon_i/Power_Monitor_0/inst/RO[0]/nolabel_line64/nolabel_line78/LUT1_inst]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets AES_PowerMon_i/Power_Monitor_0/inst/RO[0]/nolabel_line64/nolabel_line77/out_INST_0]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets AES_PowerMon_i/Power_Monitor_0/inst/RO[1]/nolabel_line64/nolabel_line77/out]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets AES_PowerMon_i/Power_Monitor_0/inst/RO[1]/nolabel_line64/nolabel_line78/LUT1_inst]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets AES_PowerMon_i/Power_Monitor_0/inst/RO[1]/nolabel_line64/nolabel_line77/out_INST_0]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets AES_PowerMon_i/Power_Monitor_0/inst/RO[2]/nolabel_line64/nolabel_line77/out]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets AES_PowerMon_i/Power_Monitor_0/inst/RO[2]/nolabel_line64/nolabel_line78/LUT1_inst]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets AES_PowerMon_i/Power_Monitor_0/inst/RO[2]/nolabel_line64/nolabel_line77/out_INST_0]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets AES_PowerMon_i/Power_Monitor_0/inst/RO[3]/nolabel_line64/nolabel_line77/out]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets AES_PowerMon_i/Power_Monitor_0/inst/RO[3]/nolabel_line64/nolabel_line78/LUT1_inst]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets AES_PowerMon_i/Power_Monitor_0/inst/RO[3]/nolabel_line64/nolabel_line77/out_INST_0]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets AES_PowerMon_i/Power_Monitor_0/inst/RO[4]/nolabel_line64/nolabel_line77/out]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets AES_PowerMon_i/Power_Monitor_0/inst/RO[4]/nolabel_line64/nolabel_line78/LUT1_inst]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets AES_PowerMon_i/Power_Monitor_0/inst/RO[4]/nolabel_line64/nolabel_line77/out_INST_0]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets AES_PowerMon_i/Power_Monitor_0/inst/RO[5]/nolabel_line64/nolabel_line77/out]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets AES_PowerMon_i/Power_Monitor_0/inst/RO[5]/nolabel_line64/nolabel_line78/LUT1_inst]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets AES_PowerMon_i/Power_Monitor_0/inst/RO[5]/nolabel_line64/nolabel_line77/out_INST_0]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets AES_PowerMon_i/Power_Monitor_0/inst/RO[6]/nolabel_line64/nolabel_line77/out]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets AES_PowerMon_i/Power_Monitor_0/inst/RO[6]/nolabel_line64/nolabel_line78/LUT1_inst]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets AES_PowerMon_i/Power_Monitor_0/inst/RO[6]/nolabel_line64/nolabel_line77/out_INST_0]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets AES_PowerMon_i/Power_Monitor_0/inst/RO[7]/nolabel_line64/nolabel_line77/out]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets AES_PowerMon_i/Power_Monitor_0/inst/RO[7]/nolabel_line64/nolabel_line78/LUT1_inst]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets AES_PowerMon_i/Power_Monitor_0/inst/RO[7]/nolabel_line64/nolabel_line77/out_INST_0]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets AES_PowerMon_i/Power_Monitor_0/inst/RO[8]/nolabel_line64/nolabel_line77/out]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets AES_PowerMon_i/Power_Monitor_0/inst/RO[8]/nolabel_line64/nolabel_line78/LUT1_inst]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets AES_PowerMon_i/Power_Monitor_0/inst/RO[8]/nolabel_line64/nolabel_line77/out_INST_0]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets AES_PowerMon_i/Power_Monitor_0/inst/RO[9]/nolabel_line64/nolabel_line77/out]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets AES_PowerMon_i/Power_Monitor_0/inst/RO[9]/nolabel_line64/nolabel_line78/LUT1_inst]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets AES_PowerMon_i/Power_Monitor_0/inst/RO[9]/nolabel_line64/nolabel_line77/out_INST_0]
