-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity aes_aes_Pipeline_VITIS_LOOP_75_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    key_and_plaintext_TVALID : IN STD_LOGIC;
    key_and_plaintext_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    key_and_plaintext_TREADY : OUT STD_LOGIC;
    key_and_plaintext_TKEEP : IN STD_LOGIC_VECTOR (0 downto 0);
    key_and_plaintext_TSTRB : IN STD_LOGIC_VECTOR (0 downto 0);
    key_and_plaintext_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    key_and_plaintext_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    key_and_plaintext_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    key_and_plaintext_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    plaintext_array_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    plaintext_array_ce0 : OUT STD_LOGIC;
    plaintext_array_we0 : OUT STD_LOGIC;
    plaintext_array_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    tmp_keep_V_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    tmp_keep_V_out_ap_vld : OUT STD_LOGIC;
    tmp_strb_V_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    tmp_strb_V_out_ap_vld : OUT STD_LOGIC;
    tmp_user_V_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    tmp_user_V_out_ap_vld : OUT STD_LOGIC;
    p_4_0_0_0115_phi_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    p_4_0_0_0115_phi_out_ap_vld : OUT STD_LOGIC;
    tmp_id_V_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    tmp_id_V_out_ap_vld : OUT STD_LOGIC;
    tmp_dest_V_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    tmp_dest_V_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of aes_aes_Pipeline_VITIS_LOOP_75_3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal icmp_ln75_fu_175_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal key_and_plaintext_TDATA_blk_n : STD_LOGIC;
    signal i_29_cast_fu_187_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_k_and_p_dest_V_fu_66 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_k_and_p_id_V_fu_70 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_k_and_p_last_V_fu_74 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_k_and_p_user_V_fu_78 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_k_and_p_strb_V_fu_82 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_k_and_p_keep_V_fu_86 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_29_fu_90 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln75_fu_181_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_209 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component aes_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component aes_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln75_fu_175_p2 = ap_const_lv1_0) and (key_and_plaintext_TVALID = ap_const_logic_0)))) and (ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    i_29_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_209)) then
                if ((icmp_ln75_fu_175_p2 = ap_const_lv1_0)) then 
                    i_29_fu_90 <= add_ln75_fu_181_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_29_fu_90 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln75_fu_175_p2 = ap_const_lv1_0) and (key_and_plaintext_TVALID = ap_const_logic_0)))) and (icmp_ln75_fu_175_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                tmp_k_and_p_dest_V_fu_66 <= key_and_plaintext_TDEST;
                tmp_k_and_p_id_V_fu_70 <= key_and_plaintext_TID;
                tmp_k_and_p_keep_V_fu_86 <= key_and_plaintext_TKEEP;
                tmp_k_and_p_last_V_fu_74 <= key_and_plaintext_TLAST;
                tmp_k_and_p_strb_V_fu_82 <= key_and_plaintext_TSTRB;
                tmp_k_and_p_user_V_fu_78 <= key_and_plaintext_TUSER;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, key_and_plaintext_TVALID, icmp_ln75_fu_175_p2, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln75_fu_181_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i) + unsigned(ap_const_lv5_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(key_and_plaintext_TVALID, icmp_ln75_fu_175_p2, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) or ((icmp_ln75_fu_175_p2 = ap_const_lv1_0) and (key_and_plaintext_TVALID = ap_const_logic_0)))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(key_and_plaintext_TVALID, icmp_ln75_fu_175_p2, ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_start_int = ap_const_logic_0) or ((icmp_ln75_fu_175_p2 = ap_const_lv1_0) and (key_and_plaintext_TVALID = ap_const_logic_0)));
    end process;


    ap_condition_209_assign_proc : process(ap_CS_fsm_state1, key_and_plaintext_TVALID, icmp_ln75_fu_175_p2, ap_start_int)
    begin
                ap_condition_209 <= (not(((ap_start_int = ap_const_logic_0) or ((icmp_ln75_fu_175_p2 = ap_const_lv1_0) and (key_and_plaintext_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, key_and_plaintext_TVALID, icmp_ln75_fu_175_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln75_fu_175_p2 = ap_const_lv1_0) and (key_and_plaintext_TVALID = ap_const_logic_0)))) and (icmp_ln75_fu_175_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_state1, key_and_plaintext_TVALID, icmp_ln75_fu_175_p2, ap_loop_exit_ready, ap_done_reg, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln75_fu_175_p2 = ap_const_lv1_0) and (key_and_plaintext_TVALID = ap_const_logic_0)))) and (ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, key_and_plaintext_TVALID, icmp_ln75_fu_175_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln75_fu_175_p2 = ap_const_lv1_0) and (key_and_plaintext_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_assign_proc : process(ap_CS_fsm_state1, i_29_fu_90, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_i <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_i <= i_29_fu_90;
        end if; 
    end process;

    i_29_cast_fu_187_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i),64));
    icmp_ln75_fu_175_p2 <= "1" when (ap_sig_allocacmp_i = ap_const_lv5_10) else "0";

    key_and_plaintext_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state1, key_and_plaintext_TVALID, icmp_ln75_fu_175_p2, ap_start_int)
    begin
        if (((icmp_ln75_fu_175_p2 = ap_const_lv1_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            key_and_plaintext_TDATA_blk_n <= key_and_plaintext_TVALID;
        else 
            key_and_plaintext_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    key_and_plaintext_TREADY_assign_proc : process(ap_CS_fsm_state1, key_and_plaintext_TVALID, icmp_ln75_fu_175_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln75_fu_175_p2 = ap_const_lv1_0) and (key_and_plaintext_TVALID = ap_const_logic_0)))) and (icmp_ln75_fu_175_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            key_and_plaintext_TREADY <= ap_const_logic_1;
        else 
            key_and_plaintext_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    p_4_0_0_0115_phi_out <= tmp_k_and_p_last_V_fu_74;

    p_4_0_0_0115_phi_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, key_and_plaintext_TVALID, icmp_ln75_fu_175_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln75_fu_175_p2 = ap_const_lv1_0) and (key_and_plaintext_TVALID = ap_const_logic_0)))) and (icmp_ln75_fu_175_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_4_0_0_0115_phi_out_ap_vld <= ap_const_logic_1;
        else 
            p_4_0_0_0115_phi_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    plaintext_array_address0 <= i_29_cast_fu_187_p1(4 - 1 downto 0);

    plaintext_array_ce0_assign_proc : process(ap_CS_fsm_state1, key_and_plaintext_TVALID, icmp_ln75_fu_175_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln75_fu_175_p2 = ap_const_lv1_0) and (key_and_plaintext_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            plaintext_array_ce0 <= ap_const_logic_1;
        else 
            plaintext_array_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    plaintext_array_d0 <= key_and_plaintext_TDATA;

    plaintext_array_we0_assign_proc : process(ap_CS_fsm_state1, key_and_plaintext_TVALID, icmp_ln75_fu_175_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln75_fu_175_p2 = ap_const_lv1_0) and (key_and_plaintext_TVALID = ap_const_logic_0)))) and (icmp_ln75_fu_175_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            plaintext_array_we0 <= ap_const_logic_1;
        else 
            plaintext_array_we0 <= ap_const_logic_0;
        end if; 
    end process;

    tmp_dest_V_out <= tmp_k_and_p_dest_V_fu_66;

    tmp_dest_V_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, key_and_plaintext_TVALID, icmp_ln75_fu_175_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln75_fu_175_p2 = ap_const_lv1_0) and (key_and_plaintext_TVALID = ap_const_logic_0)))) and (icmp_ln75_fu_175_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            tmp_dest_V_out_ap_vld <= ap_const_logic_1;
        else 
            tmp_dest_V_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tmp_id_V_out <= tmp_k_and_p_id_V_fu_70;

    tmp_id_V_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, key_and_plaintext_TVALID, icmp_ln75_fu_175_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln75_fu_175_p2 = ap_const_lv1_0) and (key_and_plaintext_TVALID = ap_const_logic_0)))) and (icmp_ln75_fu_175_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            tmp_id_V_out_ap_vld <= ap_const_logic_1;
        else 
            tmp_id_V_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tmp_keep_V_out <= tmp_k_and_p_keep_V_fu_86;

    tmp_keep_V_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, key_and_plaintext_TVALID, icmp_ln75_fu_175_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln75_fu_175_p2 = ap_const_lv1_0) and (key_and_plaintext_TVALID = ap_const_logic_0)))) and (icmp_ln75_fu_175_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            tmp_keep_V_out_ap_vld <= ap_const_logic_1;
        else 
            tmp_keep_V_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tmp_strb_V_out <= tmp_k_and_p_strb_V_fu_82;

    tmp_strb_V_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, key_and_plaintext_TVALID, icmp_ln75_fu_175_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln75_fu_175_p2 = ap_const_lv1_0) and (key_and_plaintext_TVALID = ap_const_logic_0)))) and (icmp_ln75_fu_175_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            tmp_strb_V_out_ap_vld <= ap_const_logic_1;
        else 
            tmp_strb_V_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tmp_user_V_out <= tmp_k_and_p_user_V_fu_78;

    tmp_user_V_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, key_and_plaintext_TVALID, icmp_ln75_fu_175_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln75_fu_175_p2 = ap_const_lv1_0) and (key_and_plaintext_TVALID = ap_const_logic_0)))) and (icmp_ln75_fu_175_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            tmp_user_V_out_ap_vld <= ap_const_logic_1;
        else 
            tmp_user_V_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

end behav;
